---
- name: Create Azure virtual machine
  hosts: localhost
  connection: local

  vars:
    resource_group_name: eficode2
    location: eastus
    vm_name: owm2
    vm_size: Standard_B2s
    vm_username: devops
    vm_password: Devops1234%^&*
    image_publisher: Canonical
    image_offer: UbuntuServer
    image_sku: 18.04-LTS
    public_ip_allocation_method: Static
    public_ip_dns_name: my-vm-dns-name

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"
        state: present

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: owm1
        address_prefixes: "10.2.0.10/24"
        state: present

    - name: Create subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group_name }}"
        virtual_network: owm1
        name: my-subnet
        address_prefix: "10.0.0.0/24"
        state: present

  #  - name: Create public IP address
  #    azure_rm_publicipaddress:
  #      resource_group: "{{ resource_group_name }}"
  #      name: my-public-ip
  #      allocation_method: "{{ public_ip_allocation_method }}"
  #      dns_name: "{{ public_ip_dns_name }}"
  #      state: present
  #
  #  - name: Create virtual machine
  #    azure_rm_virtualmachine:
  #      resource_group: "{{ resource_group_name }}"
  #      name: "{{ vm_name }}"
  #      vm_size: "{{ vm_size }}"
  #      admin_username: "{{ vm_username }}"
  #      admin_password: "{{ vm_password }}"
  #      image:
  #        publisher: "{{ image_publisher }}"
  #        offer: "{{ image_offer }}"
  #        sku: "{{ image_sku }}"
  #        version: latest
  #      network_interfaces:
  #        - name: my-nic
  #          ip_configurations:
  #            - name: my-ip-config
  #              subnet: my-subnet
  #              public_ip_address: my-public-ip
  #      state: present

